//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQPhone.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FAQPhone.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار.
        /// </summary>
        internal static string account_credit {
            get {
                return ResourceManager.GetString("account_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابطال.
        /// </summary>
        internal static string cancelation {
            get {
                return ResourceManager.GetString("cancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزاحم.
        /// </summary>
        internal static string cancelation_annoying {
            get {
                return ResourceManager.GetString("cancelation_annoying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال شما مزاحمت تلقی شده بنابر این مقداری از وجه شما کسر شده و باقی آن بازگردانده میشود و در صورت تکرار ممکن است کاربری شما غیر فعال شود.
        /// </summary>
        internal static string cancelation_annoying_text {
            get {
                return ResourceManager.GetString("cancelation_annoying_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توهین آمیز.
        /// </summary>
        internal static string cancelation_offensiv {
            get {
                return ResourceManager.GetString("cancelation_offensiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال شما توهین تلقی شده بنابر این مقداری از وجه شما کسر شده و باقی آن بازگردانده میشود و در صورت تکرار ممکن است کاربری شما غیر فعال شود.
        /// </summary>
        internal static string cancelation_offensiv_text {
            get {
                return ResourceManager.GetString("cancelation_offensiv_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناواضح.
        /// </summary>
        internal static string cancelation_unclear {
            get {
                return ResourceManager.GetString("cancelation_unclear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال شما واضح نیست بنابراین وجه شما بازگردانده می شود و شما باید سوال خود را بار دیگر و به طور واضح بپرسید.
        /// </summary>
        internal static string cancelation_unclear_text {
            get {
                return ResourceManager.GetString("cancelation_unclear_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامربوط.
        /// </summary>
        internal static string cancelation_unrelated {
            get {
                return ResourceManager.GetString("cancelation_unrelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال شما به بخش انتحاب شده مربوط نیست بنابراین وجه شما بازگردانده می شود و شما باید سوال خود را بار دیگر و در بخش صحیح بپرسید.
        /// </summary>
        internal static string cancelation_unrelated_text {
            get {
                return ResourceManager.GetString("cancelation_unrelated_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گفتگو.
        /// </summary>
        internal static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیغام.
        /// </summary>
        internal static string chat_text {
            get {
                return ResourceManager.GetString("chat_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید کد.
        /// </summary>
        internal static string checkcode {
            get {
                return ResourceManager.GetString("checkcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ.
        /// </summary>
        internal static string command_accept {
            get {
                return ResourceManager.GetString("command_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افرودن.
        /// </summary>
        internal static string command_add {
            get {
                return ResourceManager.GetString("command_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        internal static string command_edit {
            get {
                return ResourceManager.GetString("command_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ و اتمام گفتگو.
        /// </summary>
        internal static string command_finish {
            get {
                return ResourceManager.GetString("command_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه.
        /// </summary>
        internal static string command_next {
            get {
                return ResourceManager.GetString("command_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string command_reject {
            get {
                return ResourceManager.GetString("command_reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابطال.
        /// </summary>
        internal static string command_report {
            get {
                return ResourceManager.GetString("command_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        internal static string command_save {
            get {
                return ResourceManager.GetString("command_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        internal static string command_select_all {
            get {
                return ResourceManager.GetString("command_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچکدام.
        /// </summary>
        internal static string command_select_none {
            get {
                return ResourceManager.GetString("command_select_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string command_send {
            get {
                return ResourceManager.GetString("command_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید کلمه عبور.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        internal static string contact_city {
            get {
                return ResourceManager.GetString("contact_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        internal static string contact_email {
            get {
                return ResourceManager.GetString("contact_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن منزل.
        /// </summary>
        internal static string contact_house {
            get {
                return ResourceManager.GetString("contact_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه.
        /// </summary>
        internal static string contact_mobile {
            get {
                return ResourceManager.GetString("contact_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        internal static string contact_province {
            get {
                return ResourceManager.GetString("contact_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن محل کار.
        /// </summary>
        internal static string contact_work {
            get {
                return ResourceManager.GetString("contact_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL.
        /// </summary>
        internal static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست.
        /// </summary>
        internal static string discussion {
            get {
                return ResourceManager.GetString("discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جواب.
        /// </summary>
        internal static string discussion_answer {
            get {
                return ResourceManager.GetString("discussion_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال جدید.
        /// </summary>
        internal static string discussion_edit {
            get {
                return ResourceManager.GetString("discussion_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن سوال.
        /// </summary>
        internal static string discussion_edit_text {
            get {
                return ResourceManager.GetString("discussion_edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان سوال.
        /// </summary>
        internal static string discussion_edit_title {
            get {
                return ResourceManager.GetString("discussion_edit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این قسمت یک عنوان مناسب برای سوال خود انتخاب کنید و برای رفتن به قسمت ارسال سوال دکمه ادامه را فشار دهید.
        /// </summary>
        internal static string discussion_edit_title_help {
            get {
                return ResourceManager.GetString("discussion_edit_title_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناس.
        /// </summary>
        internal static string discussion_operator {
            get {
                return ResourceManager.GetString("discussion_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال.
        /// </summary>
        internal static string discussion_question {
            get {
                return ResourceManager.GetString("discussion_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان قابل نمایش.
        /// </summary>
        internal static string discussion_recive_display {
            get {
                return ResourceManager.GetString("discussion_recive_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        internal static string discussion_recive_price {
            get {
                return ResourceManager.GetString("discussion_recive_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دربافت سوال.
        /// </summary>
        internal static string discussion_revice {
            get {
                return ResourceManager.GetString("discussion_revice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نمایه ها.
        /// </summary>
        internal static string discussion_select_tags {
            get {
                return ResourceManager.GetString("discussion_select_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایه جدید.
        /// </summary>
        internal static string discussion_tag_new {
            get {
                return ResourceManager.GetString("discussion_tag_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایه ها.
        /// </summary>
        internal static string discussion_tags {
            get {
                return ResourceManager.GetString("discussion_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تحصیلی.
        /// </summary>
        internal static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجه.
        /// </summary>
        internal static string education_grade {
            get {
                return ResourceManager.GetString("education_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح.
        /// </summary>
        internal static string education_level {
            get {
                return ResourceManager.GetString("education_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه.
        /// </summary>
        internal static string education_major {
            get {
                return ResourceManager.GetString("education_major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانشگاه.
        /// </summary>
        internal static string education_university {
            get {
                return ResourceManager.GetString("education_university", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرایند ثبت نام با اشکال مواجه شده.
        /// </summary>
        internal static string err_securitycode_failed {
            get {
                return ResourceManager.GetString("err_securitycode_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این شماره موبایل قبلا ثبت نام نشده.
        /// </summary>
        internal static string err_securitycode_mobilenotfound {
            get {
                return ResourceManager.GetString("err_securitycode_mobilenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی اشتباه است.
        /// </summary>
        internal static string err_securitycode_notmatch {
            get {
                return ResourceManager.GetString("err_securitycode_notmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراموشی کلمه عبور.
        /// </summary>
        internal static string forgetpassword {
            get {
                return ResourceManager.GetString("forgetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکانات نرم افزار.
        /// </summary>
        internal static string mainpage {
            get {
                return ResourceManager.GetString("mainpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرشیو.
        /// </summary>
        internal static string operator_archived_faq {
            get {
                return ResourceManager.GetString("operator_archived_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرم افزار کارشناس.
        /// </summary>
        internal static string operator_faq {
            get {
                return ResourceManager.GetString("operator_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در دست اقدام.
        /// </summary>
        internal static string operator_inprogress_faq {
            get {
                return ResourceManager.GetString("operator_inprogress_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت سوال.
        /// </summary>
        internal static string operator_receive_faq {
            get {
                return ResourceManager.GetString("operator_receive_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شخصی.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل تولد.
        /// </summary>
        internal static string profile_birthPlace {
            get {
                return ResourceManager.GetString("profile_birthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        internal static string profile_fatherName {
            get {
                return ResourceManager.GetString("profile_fatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string profile_firstName {
            get {
                return ResourceManager.GetString("profile_firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        internal static string profile_lastName {
            get {
                return ResourceManager.GetString("profile_lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی.
        /// </summary>
        internal static string profile_nationalCode {
            get {
                return ResourceManager.GetString("profile_nationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        internal static string profile_no {
            get {
                return ResourceManager.GetString("profile_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل صدور.
        /// </summary>
        internal static string profile_placeOfIssues {
            get {
                return ResourceManager.GetString("profile_placeOfIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور.
        /// </summary>
        internal static string resetpassword {
            get {
                return ResourceManager.GetString("resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی.
        /// </summary>
        internal static string securitycode {
            get {
                return ResourceManager.GetString("securitycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب بخش.
        /// </summary>
        internal static string select_department {
            get {
                return ResourceManager.GetString("select_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال کد امنیتی.
        /// </summary>
        internal static string sendcode {
            get {
                return ResourceManager.GetString("sendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سامانه.
        /// </summary>
        internal static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از سامانه.
        /// </summary>
        internal static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرشیو.
        /// </summary>
        internal static string user_archived_faq {
            get {
                return ResourceManager.GetString("user_archived_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال جدید.
        /// </summary>
        internal static string user_create_faq {
            get {
                return ResourceManager.GetString("user_create_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرم افزار کاربر.
        /// </summary>
        internal static string user_faq {
            get {
                return ResourceManager.GetString("user_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظر پاسخ.
        /// </summary>
        internal static string user_inprogress_faq {
            get {
                return ResourceManager.GetString("user_inprogress_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
